name: chunked_uploader
description: An easy-to-use package to upload files in chunks using Dio for mobile, desktop and web.
version: 2.0.0
homepage: https://github.com/Taskulu/chunked_uploader
repository: https://github.com/Taskulu/chunked_uploader

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.2.1
  universal_io: ^2.2.2
  async: ^2.11.0
